from app import db


class User(db.Model):
    """Table representing registered users.

    Database Columns:
        id -- Identification number automatically generated by database.
        name -- The name/nickname the user uses on the site.
        email -- The user's email address.
        role_id -- ID number of a Role.
    """
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    email = db.Column(db.String(254), unique=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))


class Role(db.Model):
    """Table representing user roles.

    Database Columns:
        id -- Auto-generated ID number.
        name -- What we call the role.
    Relationships:
        users -- Link role to User.
    """
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    users = db.relationship('User', backref='role', lazy='dynamic')
